"""Finding model + report formatting (markdown / JSON).

A ``Finding`` is one reviewable observation. Deterministic checks emit them
directly; the Claude skill appends judgment findings of the same shape so the
final report is uniform regardless of source.
"""

from __future__ import annotations

import dataclasses
import json
from dataclasses import dataclass, field, asdict
from enum import Enum


class Severity(str, Enum):
    """Ordered worst -> least. ``rank`` drives sorting."""

    BLOCKER = "blocker"   # will not work / will not build / unsafe
    MAJOR = "major"       # likely to cause a real problem
    MINOR = "minor"       # should fix, not urgent
    NIT = "nit"           # style / hygiene
    INFO = "info"         # context, not an issue

    @property
    def rank(self) -> int:
        return {"blocker": 0, "major": 1, "minor": 2, "nit": 3, "info": 4}[self.value]


class Domain(str, Enum):
    ELECTRICAL = "electrical"        # ERC, connectivity, missing drivers
    POWER_THERMAL = "power_thermal"  # trace sizing, copper, regulators
    SIGNAL_INTEGRITY = "signal_integrity"
    DFM = "dfm"                      # manufacturability, parity, footprints
    BOM = "bom"                      # sourcing / part hygiene
    HYGIENE = "hygiene"             # schematic/layout cleanliness, suppressions


@dataclass
class Finding:
    """One reviewable observation.

    ``location`` is a free-form dict (any of: sheet, refdes, net, layer, xy).
    ``evidence`` names the check or image that produced it. ``check`` is the
    stable id of the producing check (for golden tests).
    """

    id: str
    severity: Severity
    domain: Domain
    title: str
    detail: str = ""
    recommendation: str = ""
    location: dict = field(default_factory=dict)
    evidence: str = ""
    check: str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["severity"] = self.severity.value
        d["domain"] = self.domain.value
        return d


def sort_findings(findings: list[Finding]) -> list[Finding]:
    return sorted(findings, key=lambda f: (f.severity.rank, f.domain.value, f.id))


def to_json(findings: list[Finding], meta: dict | None = None) -> str:
    return json.dumps(
        {
            "meta": meta or {},
            "summary": _summary_counts(findings),
            "findings": [f.to_dict() for f in sort_findings(findings)],
        },
        indent=2,
    )


def _summary_counts(findings: list[Finding]) -> dict:
    by_sev: dict[str, int] = {}
    by_dom: dict[str, int] = {}
    for f in findings:
        by_sev[f.severity.value] = by_sev.get(f.severity.value, 0) + 1
        by_dom[f.domain.value] = by_dom.get(f.domain.value, 0) + 1
    return {"total": len(findings), "by_severity": by_sev, "by_domain": by_dom}


_SEV_ICON = {
    "blocker": "🛑", "major": "🔴", "minor": "🟡", "nit": "⚪", "info": "ℹ️",
}


def to_markdown(findings: list[Finding], meta: dict | None = None) -> str:
    """Human-readable report. The skill embeds this and adds the visual /
    datasheet judgment findings on top."""
    meta = meta or {}
    out: list[str] = []
    title = meta.get("project", "KiCad design")
    out.append(f"# Design review — {title}")
    if meta.get("kicad_version"):
        out.append(f"\n_KiCad {meta['kicad_version']} · generated by kicad-review_\n")
    counts = _summary_counts(findings)
    sev = counts["by_severity"]
    out.append(
        "**Findings:** "
        + ", ".join(
            f"{_SEV_ICON.get(s,'')} {sev.get(s,0)} {s}"
            for s in ("blocker", "major", "minor", "nit")
            if sev.get(s)
        )
        + f"  (total {counts['total']})\n"
    )

    sf = sort_findings(findings)
    # group by domain within severity-sorted order, but present by domain section
    domains_present = []
    for f in sf:
        if f.domain not in domains_present:
            domains_present.append(f.domain)
    for dom in domains_present:
        out.append(f"\n## {dom.value.replace('_', ' ').title()}\n")
        for f in [x for x in sf if x.domain == dom]:
            loc = ", ".join(f"{k}={v}" for k, v in f.location.items() if v)
            out.append(f"### {_SEV_ICON.get(f.severity.value,'')} [{f.severity.value}] {f.title}")
            if loc:
                out.append(f"*Location:* {loc}  ")
            if f.detail:
                out.append(f"\n{f.detail}\n")
            if f.recommendation:
                out.append(f"**Recommendation:** {f.recommendation}\n")
            if f.evidence:
                out.append(f"<sub>evidence: {f.evidence}</sub>\n")
    if not sf:
        out.append("\n_No deterministic findings. Proceed to visual + datasheet review._\n")
    return "\n".join(out)
